### ISSUE TITLE
About the evaluation of targeted caption

### ISSUE THREAD

**Issue by xuyan1115** [huanzhang12/ImageCaptioningAttack#1]
Hi, 
I want to ask a question about the targeted caption experiment.
You randomly select only one image as the target caption  of 1000 val images in your experiment to get 95.8% result. I am afraid that whether there is a contingency? (maybe some selected target caption are easy to attack, the others are hard to attack)

**Comment by chenhongge** [comment]
Hi,
Thanks for your question!
Actually, for each test image, we randomly select its target caption. Not one target caption for all 1000 images, but 1000 target captions for 1000 images. 
You may check this line of the code:
[https://github.com/huanzhang12/ImageCaptioningAttack/blob/97078e354081b78398e0d4443984822c954daff5/im2txt/run_attack_BATCH_search_C.py#L223](url)
Let us know if you have any other questions.

**Comment by xuyan1115** [comment]
Hi, 
I have another question: 
I run your code and find that some images generate their targeted captions with extra phrase, like this:

targeted caption:     "a person holding a doughnut with a doughnut."
caption after attack: "a person holding a doughnut with a doughnut **in his hand**."

I want to ask that whether this is a successful attack or not?

**Comment by chenhongge** [comment]
No. This is not successful. A successful attack means inference caption is exactly the same as the targeted caption.
